# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
# メール送信サーバの設定(gmail)
delivery_method:           smtp
smtp_enable_starttls_auto: true
smtp_address:              smtp.gmail.com
smtp_port:                 587
smtp_domain:               gmail.com
smtp_authentication:       plain
smtp_user_name:            kim.kyp.7418@gmail.com
smtp_password:             noqjkulynavlmvcu


# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
